// Generated by CoffeeScript 2.7.0
var MyFileProcessor, fp;

import {
  defined,
  LOG
} from '@jdeighan/base-utils';

import {
  FileProcessor
} from '@jdeighan/FileProcessor';

MyFileProcessor = class MyFileProcessor extends FileProcessor {
  begin() {
    this.count = 0;
  }

  // ..........................................................
  filterFile(hFileInfo) {
    return hFileInfo.ext === '.zh';
  }

  // ..........................................................
  beginFile(hFileInfo) {
    LOG(`FILE: ${hFileInfo.fileName}`);
  }

  // ..........................................................
  handleLine(line, lineNum, hFileInfo) {
    var _, lAst, lMatches, num, word;
    lMatches = line.match(/^(\**)\s+(\S+)/); // leading asterisks
    if (defined(lMatches)) {
      [_, lAst, word] = lMatches;
      num = lAst.length;
      console.log(`${num} ${word}`);
      this.count += 1;
      if (this.count === 10) {
        return {
          abort: true
        };
      }
    }
  }

};

fp = new MyFileProcessor('./test/');

fp.go();
